import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const spaceGrotesk = localFont({
  src: "../../public/font/SpaceGrotesk-VariableFont_wght.ttf",
  variable: "--font-space-grotesk",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Sushant Aryal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={spaceGrotesk.variable}>
      <body className={`antialiased`}>
        <div className="overflow-y-scroll">
          {children}
        </div>
      </body>
    </html>
  );
}
