import type { Metadata } from "next";
import "./globals.css";
import NavigationBar from "@/component/NavBar";
import Footer from "@/component/Footer";

export const metadata: Metadata = {
  title: "Sushant Aryal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <NavigationBar />
        <div className="w-[100vw] h-[100vh] overflow-y-scroll">
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
